---
# Variables here are applicable to 'hybrid' host groups.

rhpam_central_controller_usr: controllerUsr
rhpam_central_controller_pwd: controllerPwd

# Enable MANAGED mode for the KIE Server.
org_kie_server_controller_user: "{{ rhpam_central_controller_usr }}"
org_kie_server_controller_pwd: "{{ rhpam_central_controller_pwd }}"
