---
# Variables here are applicable to 'hybrid' host groups.

# kie-server role user needs to match logged in user in BC, otherwise it cannot access process data.
rhpam_central_admin_usr: adminUser
rhpam_central_admin_pwd: password
rhpam_server_users:
  - user: apiUser
    password: password
    roles: kie-server
  - user: "{{ rhpam_central_admin_usr }}"
    password: "{{ rhpam_central_admin_pwd }}"
    roles: kie-server,Administrators
  - user: shadowman
    password: password
    roles: redhat

rhpam_central_controller_usr: controllerUsr
rhpam_central_controller_pwd: controllerPwd

# Enable MANAGED mode for the KIE Server.
org_kie_server_controller: ws://localhost:8080/business-central/websocket/controller
org_kie_server_controller_user: "{{ rhpam_central_controller_usr }}"
org_kie_server_controller_pwd: "{{ rhpam_central_controller_pwd }}"
