---
# Variables here are applicable to 'hybrid' host groups.

# kie-server role user needs to match logged in user in BC, otherwise it cannot access process data.
rhpam_central_admin_usr: adminUser
rhpam_server_kieserver_usr: "{{ rhpam_central_admin_usr }}"

rhpam_central_controller_usr: controllerUsr
rhpam_central_controller_pwd: controllerPwd

# Enable MANAGED mode for the KIE Server.
org_kie_server_controller: ws://localhost:8080/business-central/websocket/controller
org_kie_server_controller_user: "{{ rhpam_central_controller_usr }}"
org_kie_server_controller_pwd: "{{ rhpam_central_controller_pwd }}"
