---
# Variables here are applicable to 'unmanaged' host group.

# Immutable KIE Server, disables the mgmt API and uses local config file.
org_kie_server_mgmt_api_disabled: "true"
org_kie_server_startup_strategy: "LocalContainersStartupStrategy"

# Business rules artifacts / containers to start up.
rhpam_server_containers:
  - containerId: rhpam-quickstart
    releaseId:
      groupId: com.juliaaano
      artifactId: rhpam-kjar
      version: "[1.0.0,)"
  # - containerId: example
  #   releaseId:
  #     groupId: com.example
  #     artifactId: example
  #     version: "[1.0.0,)"
