---
# This playbook can install Red Hat Decision Manager in multiple flavours:

# 1. RHPAM Central (Business Central / Workbench).
- name: provision RHPAM Central
  hosts: central
  tasks:
    - import_role:
        name: rhpam-central
    - import_role:
        name: jboss-eap-service
      vars:
        jboss_eap_svc_home: "{{ jboss_eap_home }}"
  post_tasks:
    - debug:
        msg:
          - "Installation dir: {{ rhpam_central_root }}"
          - "URL: http://{{ inventory_hostname }}:{{ jboss_http_port_number }}/business-central"
          - "User admin username: {{ rhpam_central_admin_usr }}"
          - "User admin password: {{ rhpam_central_admin_pwd }}"
          - "SSH key: {{ openssh_keypair.public_key }}"

# 2. RHPAM Server (KIE Server) unmanaged or managed, via the 'org_kie_server_controller' variable.
- name: provision RHPAM Server
  hosts: managed:unmanaged
  tasks:
    - import_role:
        name: rhpam-server
    - import_role:
        name: jboss-eap-service
      vars:
        jboss_eap_svc_home: "{{ jboss_eap_home }}"
  post_tasks:
    - debug:
        msg:
          - "Installation dir: {{ rhpam_server_root }}"
          - "URL: http://{{ inventory_hostname }}:{{ org_kie_server_http_port }}/kie-server/services/rest/server"
          - "User kieserver username: {{ rhpam_server_kieserver_usr }}"
          - "User kieserver password: {{ rhpam_server_kieserver_pwd }}"

# 3. RHPAM Central and Server on the same host.
#    The KIE Server is in managed mode and automatically connected to Central's contoller instance.
- name: provision RHPAM Central and RHPAM Server on the same host
  hosts: hybrid
  tasks:
    - include_role:
        name: rhpam-central
      vars:
        jboss_socket_binding_port_offset_number: 0
    - include_role:
        name: rhpam-server
      vars:
        jboss_socket_binding_port_offset_number: 100
        org_kie_server_controller: ws://localhost:8080/business-central/websocket/controller
        # org_kie_server_http_port: 8180 FIXME ends up as 8280
  post_tasks:
    - debug:
        msg:
          - "Run Central: $RHPAM_CENTRAL_HOME/bin/standalone.sh -c standalone-full.xml"
          - "Run Server: $RHPAM_SERVER_HOME/bin/standalone.sh -c standalone-full.xml"
          - "Central URL: http://{{ inventory_hostname }}:8080/business-central"
          - "Server URL: http://{{ inventory_hostname }}:8180/kie-server/services/rest/server"
      tags: debug
