---
- name: create {{ rhpam_server_data }} directory
  file:
    path: "{{ rhpam_server_data }}"
    state: directory

- name: add users and roles
  command: "{{ rhpam_server_home }}/bin/add-user.sh -a --user {{ item.user }} --password {{ item.password }} --role {{ item.roles }}"
  loop: "{{ rhpam_server_users }}"

- name: create {{ kie_maven_settings_custom }}
  template:
    src: settings.xml.j2
    dest: "{{ kie_maven_settings_custom }}"

- name: create setup.cli
  template:
    src: setup.cli.j2
    dest: "{{ rhpam_server_temp }}/setup.cli"

- name: run setup.cli JBoss configuration
  command: "{{ rhpam_server_home }}/bin/jboss-cli.sh --file={{ rhpam_server_temp }}/setup.cli"
